### ISSUE TITLE
Unable to grab external ladders and re-enter pods during eva in orbit or flight

### ISSUE THREAD

**Issue by KassIsLegend** [FirstPersonKSP/Kerbal-VR#325] opened 2024-05-29 01:24 UTC
Tried to get back into my pod during eva on a test mission and was unable to. I was unable to grab any of the ladder areasor anywhere on the pod, i was also unable to grab the red handle to turn it. i went out of vr mode to get my kerbal back into the pod (an Mk1-3 command pod) with mouse and keyboard and re-entered in vr mode. after reaching the ground safely i went EVA again and this time i was able to grab onto all areas i was supposed to, ladders and all and get back into the pod. i got curious and experimented a bit. these are the following setups i used, starting off on the launchpad, both i was able to fully interact, enter, grab and exit on the ground and on the pad. Both i had the same issue with in orbit (using the set orbit cheat in the cheat menu to quickly get into a LEO) where i was completely unable to grab and enter the pods.

Top->Bottom pod setup:
Launch escape system
TS-12 Stack seperator
Mk1-3 command pod
Heat Shield 2.5m
TD-25 Decoupler
Ground test: Pass
Orbit test: fail. Unable to grab and enter pod

Launch escape system
Clamp-O-Tron Docking Port Sr.
Mk2 Lander Can
PICA-K Advanced HeatShield
TD-25 Decoupler
Ground test: Pass
Orbit Test: Fail. Unable to grab and enter pod

again to note: This is external grabbing and interactions only, everything interior wise is perfectly fine

[KSP.log](https://github.com/FirstPersonKSP/Kerbal-VR/files/15477453/KSP.log)

**Comment by JonnyOThan** [comment] 2024-05-29 02:19
Seems like this is likely caused by the KSPCF same vessel collision performance patch.

**Comment by JonnyOThan** [comment] 2024-05-29 02:32
Dupe of #322

**Closed** 2024-05-29 02:31 UTC
Labels: bug
